// GENERATED by scripts/site-sequences.mjs from registry/assets/site/raw/sequences.json — do not edit.
export interface Step {
  file: string
  title: string
  caption: string
  width: number
  height: number
}
export const SEQUENCES: Readonly<Record<string, readonly Step[]>> = {
  "canvas": [
    {
      "file": "seq-canvas-1.jpg",
      "title": "The crew on the canvas",
      "caption": "Framed the crew in the harness view: every agent card shows what it is doing right now — the brief it was given, the tool call it is on and the status line under it — with the spec notes each was handed in a row beneath, the browser cards under those, and the cables drawn as shared trunks along the gutters.",
      "width": 1400,
      "height": 874
    },
    {
      "file": "seq-canvas-2.jpg",
      "title": "An agent card opened, the rail scrubbed",
      "caption": "Clicked Fresco open and dragged its checkpoint rail upward: the transcript on the left holds the turns it has taken, the live terminal runs under the LIVE line, and the rail fanned out into the 132 checkpoints with the title each turn was given.",
      "width": 1400,
      "height": 875
    },
    {
      "file": "seq-canvas-3.jpg",
      "title": "An agent stops to ask, and is answered on the card",
      "caption": "Velvet reached a decision it would not take alone: its card went to attention, it printed the two choices into its own terminal, and the answer was typed straight onto the card — one line, and the agent carried on from there.",
      "width": 1400,
      "height": 875
    }
  ],
  "harnesses": [
    {
      "file": "seq-harnesses-1.jpg",
      "title": "The harness picker, Shell chosen",
      "caption": "Pressed TERMINAL in the dock over the harness canvas and chose SHELL: the picker shows the five harnesses Cookrew ships — Claude Code, Codex, OpenCode, Pi and a plain shell — with Shell lit and + IMPORT A TEAM at the end of the row.",
      "width": 1400,
      "height": 875
    },
    {
      "file": "seq-harnesses-2.jpg",
      "title": "Claude Code chosen",
      "caption": "Chose CLAUDE CODE in the same picker: the lit chip moved from Shell to Claude Code, and a click on the canvas would now place an agent on that harness. The crew behind it is already mixed — Codex, OpenCode and Pi all answer on this board.",
      "width": 1400,
      "height": 875
    },
    {
      "file": "seq-harnesses-3.jpg",
      "title": "Import a team, opened",
      "caption": "Pressed + IMPORT A TEAM: the sheet opened over the canvas with its address field, and under it the teams saved on this machine — private, visible to nobody else, placed as a session with one press.",
      "width": 1400,
      "height": 875
    }
  ],
  "checkpoints": [
    {
      "file": "seq-checkpoints-1.jpg",
      "title": "A card open on its rail",
      "caption": "Clicked Magpie open: its latest turn sits above the LIVE line, the live terminal runs under it, and the rail on the right counts 78 checkpoints over the session’s whole chain.",
      "width": 1400,
      "height": 875
    },
    {
      "file": "seq-checkpoints-2.jpg",
      "title": "Mid-scrub on the rail",
      "caption": "Pressed the orchestrator’s rail at its live end and dragged upward: the list of 311 checkpoints fanned out with the title each turn was given, the focus riding the drag, and the transcript on the left following it.",
      "width": 1400,
      "height": 875
    },
    {
      "file": "seq-checkpoints-3.jpg",
      "title": "Fork offered on a row",
      "caption": "Held the pointer on a row of the fanned list until its action surfaced: FORK, which starts a new agent from that checkpoint and leaves the original running, untouched.",
      "width": 1400,
      "height": 875
    }
  ],
  "board": [
    {
      "file": "seq-board-1.jpg",
      "title": "The Board, one row per agent",
      "caption": "Switched the header from Canvas to Board: one row per agent with its harness, role and workspace chips, the prompt it was last given, what it is doing now and its checkpoint count — and Velvet’s row in red, because it has stopped to ask its owner which way to go.",
      "width": 1400,
      "height": 875
    },
    {
      "file": "seq-board-2.jpg",
      "title": "A facet chip narrows the roster",
      "caption": "Focused the Board’s search so the facet bar opened, then clicked CLAUDE CODE: the roster dropped to the five agents on that harness and CLEAR appeared at the head of the bar. The chips count the rest — Codex 1, OpenCode 1, Pi 1 — and one more per role.",
      "width": 1400,
      "height": 875
    },
    {
      "file": "seq-board-3.jpg",
      "title": "Searched the checkpoints",
      "caption": "Typed checkpoint into the Board’s search: every agent answered, and each row carries the checkpoint the hit landed in — T131, T121 — with the words around it, read from the agents’ own transcripts rather than from a log.",
      "width": 1400,
      "height": 875
    }
  ],
  "cli": [
    {
      "file": "seq-cli-1.jpg",
      "title": "cookrew list, in a plain shell card",
      "caption": "Opened a Shell card on the same canvas: cookrew list printed the crew with each one’s role and harness, and cookrew ask sent Vigil a brief it will answer in its own card — the same command line an orchestrating agent types.",
      "width": 1400,
      "height": 878
    }
  ],
  "mobile": [
    {
      "file": "seq-mobile-1.jpg",
      "title": "The canvas at phone width",
      "caption": "Rendered the same canvas at 390 px with touch emulation, the layout the phone companion serves: the cards keep their turn, their harness chip and their checkpoint count, and the dock sits along the bottom.",
      "width": 700,
      "height": 1400
    },
    {
      "file": "seq-mobile-2.jpg",
      "title": "A waiting card, tapped open on the phone",
      "caption": "Tapped the card that wanted an answer: it takes the screen with NEEDS ATTENTION beside its name, the ask at the top, the rail counting 124 down the right edge, and the phone’s own key row under it.",
      "width": 700,
      "height": 1400
    },
    {
      "file": "seq-mobile-3.jpg",
      "title": "The Board on the phone",
      "caption": "Tapped BOARD on the phone: the same roster in the narrow layout, each row carrying its harness and role chips and what the agent last did — and NEEDS YOU on the one that stopped to ask.",
      "width": 700,
      "height": 1400
    },
    {
      "file": "seq-mobile-4.jpg",
      "title": "The dock picker on the phone",
      "caption": "Tapped TERMINAL in the phone’s dock: the harness picker opened above it with the five harnesses and + IMPORT A TEAM — the same row the desktop shows, at thumb size.",
      "width": 700,
      "height": 1400
    }
  ],
  "workspaces": [
    {
      "file": "seq-workspaces-1.jpg",
      "title": "The workspace wall",
      "caption": "Pressed the workspace pill: the wall slid in as tilted screens, Cookrew Dev picked in front with a snapshot of this canvas and its directory under it, the others behind, and BACK, DIRECTORIES, REMOVE and HISTORY below.",
      "width": 1400,
      "height": 875
    }
  ],
  "marketplace": [
    {
      "file": "seq-marketplace-1.jpg",
      "title": "The marketplace, and the seats you already hold",
      "caption": "Opened cookrew.dev/market signed in: the Your agents strip lists the doors this account can open right now — one it serves itself, one it was granted a seat at — above the finder and the shelf of teams taking calls.",
      "width": 1400,
      "height": 875
    },
    {
      "file": "seq-marketplace-2.jpg",
      "title": "A team page: one line, one strip",
      "caption": "Opened a priced team page as a reader holding no seat: the page is one line — who answers, for how many agents, over which transports — above one strip carrying the team’s own terminal and its checkpoints, with BUY A SEAT · $1 beside the line.",
      "width": 1400,
      "height": 875
    }
  ]
}
