/**
 * A QR encoder, byte mode, error correction L/M/Q/H, versions 1 to 10.
 *
 * WHY THIS IS HERE AND NOT A DEPENDENCY. The pairing popout has to draw a QR
 * in the renderer. The one QR library in the tree is `qrcode-terminal`, which
 * writes block characters to a TTY from the CLI — it is a printer, not an
 * encoder, and nothing in the browser bundle can use it. The alternative was a
 * new runtime dependency in the one window that shows a credential.
 *
 * Scope is deliberately narrow: one mode, four correction levels, ten
 * versions. That covers every string this app puts on a screen — a 55-byte
 * pairing payload, a legacy tailnet URL with a token on it at about 80, and a
 * ~133-byte otpauth enrolment URL — with room left over, and it leaves out the
 * numeric/alphanumeric/kanji modes, the ECI header and structured append,
 * which nothing here would ever emit.
 *
 * Correctness is not argued, it is checked TWICE. The tests compare whole
 * matrices, module for module, against fixtures generated by an independent
 * reference implementation at every version and every level — and then they
 * DECODE what this file produces, unmasking, de-interleaving and running the
 * Reed-Solomon syndromes to zero before reading the payload back out. A QR
 * that renders but does not scan is worse than no QR, and a shape test would
 * not catch one. The first sweep of ten versions at one level missed a mask
 * disagreement on one payload in nine; a sweep of forty found it at once.
 */

export type QrLevel = 'L' | 'M' | 'Q' | 'H'

export const QR_LEVELS: readonly QrLevel[] = ['L', 'M', 'Q', 'H']

/** Total codewords per version — data plus error correction, all levels. */
const TOTAL_CODEWORDS = [0, 26, 44, 70, 100, 134, 172, 196, 242, 292, 346]

/**
 * Error-correction codewords PER BLOCK, and how the data splits into blocks.
 *
 * `blocks` is [group 1 count, group 2 count]. The lengths are not tabled
 * because they are forced: group 2's blocks are always exactly one codeword
 * longer than group 1's, so `floor(data / blocks)` and `+1` reproduce the
 * standard's table exactly — v8-M's 2x38 + 2x39, v10-Q's 6x19 + 2x20 — and
 * a table that can be derived is a table that can be typed in wrong.
 */
const EC: Record<QrLevel, { ec: number; blocks: readonly [number, number] }[]> = {
  L: [
    { ec: 0, blocks: [0, 0] },
    { ec: 7, blocks: [1, 0] },
    { ec: 10, blocks: [1, 0] },
    { ec: 15, blocks: [1, 0] },
    { ec: 20, blocks: [1, 0] },
    { ec: 26, blocks: [1, 0] },
    { ec: 18, blocks: [2, 0] },
    { ec: 20, blocks: [2, 0] },
    { ec: 24, blocks: [2, 0] },
    { ec: 30, blocks: [2, 0] },
    { ec: 18, blocks: [2, 2] }
  ],
  M: [
    { ec: 0, blocks: [0, 0] },
    { ec: 10, blocks: [1, 0] },
    { ec: 16, blocks: [1, 0] },
    { ec: 26, blocks: [1, 0] },
    { ec: 18, blocks: [2, 0] },
    { ec: 24, blocks: [2, 0] },
    { ec: 16, blocks: [4, 0] },
    { ec: 18, blocks: [4, 0] },
    { ec: 22, blocks: [2, 2] },
    { ec: 22, blocks: [3, 2] },
    { ec: 26, blocks: [4, 1] }
  ],
  Q: [
    { ec: 0, blocks: [0, 0] },
    { ec: 13, blocks: [1, 0] },
    { ec: 22, blocks: [1, 0] },
    { ec: 18, blocks: [2, 0] },
    { ec: 26, blocks: [2, 0] },
    { ec: 18, blocks: [2, 2] },
    { ec: 24, blocks: [4, 0] },
    { ec: 18, blocks: [2, 4] },
    { ec: 22, blocks: [4, 2] },
    { ec: 20, blocks: [4, 4] },
    { ec: 24, blocks: [6, 2] }
  ],
  H: [
    { ec: 0, blocks: [0, 0] },
    { ec: 17, blocks: [1, 0] },
    { ec: 28, blocks: [1, 0] },
    { ec: 22, blocks: [2, 0] },
    { ec: 16, blocks: [4, 0] },
    { ec: 22, blocks: [2, 2] },
    { ec: 28, blocks: [4, 0] },
    { ec: 26, blocks: [4, 1] },
    { ec: 26, blocks: [4, 2] },
    { ec: 24, blocks: [4, 4] },
    { ec: 28, blocks: [6, 2] }
  ]
}

/** The two bits the format string carries for each level. NOT their order. */
const LEVEL_BITS: Record<QrLevel, number> = { L: 0b01, M: 0b00, Q: 0b11, H: 0b10 }

/** Alignment-pattern centre coordinates per version. */
const ALIGNMENT = [
  [], [], [6, 18], [6, 22], [6, 26], [6, 30], [6, 34],
  [6, 22, 38], [6, 24, 42], [6, 26, 46], [6, 28, 50]
]

export const QR_MAX_VERSION = 10

const size = (version: number): number => version * 4 + 17

const blockCount = (version: number, level: QrLevel): number =>
  EC[level][version].blocks[0] + EC[level][version].blocks[1]

const ecCodewords = (version: number, level: QrLevel): number =>
  EC[level][version].ec * blockCount(version, level)

/** Data codewords — everything the payload, its header and its padding fill. */
export const qrDataCodewords = (version: number, level: QrLevel = 'M'): number =>
  TOTAL_CODEWORDS[version] - ecCodewords(version, level)

/** Byte-mode payload capacity, in bytes. */
export const qrCapacity = (version: number, level: QrLevel = 'M'): number => {
  // 4 bits of mode + the character-count field, rounded down to whole bytes.
  const countBits = version < 10 ? 8 : 16
  return Math.floor((qrDataCodewords(version, level) * 8 - 4 - countBits) / 8)
}

// ---------------------------------------------------------------- GF(256) --

const EXP = new Uint8Array(512)
const LOG = new Uint8Array(256)
{
  let x = 1
  for (let i = 0; i < 255; i++) {
    EXP[i] = x
    LOG[x] = i
    x <<= 1
    if (x & 0x100) x ^= 0x11d
  }
  for (let i = 255; i < 512; i++) EXP[i] = EXP[i - 255]
}

const gfMul = (a: number, b: number): number =>
  a === 0 || b === 0 ? 0 : EXP[LOG[a] + LOG[b]]

/** The generator polynomial for `degree` error-correction codewords. */
const generator = (degree: number): Uint8Array => {
  let poly = Uint8Array.from([1])
  for (let i = 0; i < degree; i++) {
    const next = new Uint8Array(poly.length + 1)
    for (let j = 0; j < poly.length; j++) {
      next[j] ^= poly[j]
      next[j + 1] ^= gfMul(poly[j], EXP[i])
    }
    poly = next
  }
  return poly
}

const reedSolomon = (data: Uint8Array, degree: number): Uint8Array => {
  const gen = generator(degree)
  const remainder = new Uint8Array(degree)
  for (const byte of data) {
    const factor = byte ^ remainder[0]
    remainder.copyWithin(0, 1)
    remainder[degree - 1] = 0
    for (let j = 0; j < degree; j++) remainder[j] ^= gfMul(gen[j + 1], factor)
  }
  return remainder
}

// ------------------------------------------------------------------ bits --

class Bits {
  private readonly bits: number[] = []

  push(value: number, length: number): void {
    for (let i = length - 1; i >= 0; i--) this.bits.push((value >> i) & 1)
  }

  get length(): number {
    return this.bits.length
  }

  toCodewords(count: number): Uint8Array {
    const out = new Uint8Array(count)
    for (let i = 0; i < this.bits.length; i++) {
      if (this.bits[i]) out[i >> 3] |= 0x80 >> (i & 7)
    }
    return out
  }
}

const utf8 = (text: string): Uint8Array => new TextEncoder().encode(text)

/** The smallest version that holds `bytes` at `level`, or null if none does. */
export const qrVersionFor = (bytes: number, level: QrLevel = 'M'): number | null => {
  for (let version = 1; version <= QR_MAX_VERSION; version++) {
    if (bytes <= qrCapacity(version, level)) return version
  }
  return null
}

const dataCodewordsFor = (text: string, version: number, level: QrLevel): Uint8Array => {
  const bytes = utf8(text)
  const total = qrDataCodewords(version, level)
  const bits = new Bits()
  bits.push(0b0100, 4) // byte mode
  bits.push(bytes.length, version < 10 ? 8 : 16)
  for (const byte of bytes) bits.push(byte, 8)
  // Terminator, up to four zero bits, then pad to a whole byte.
  const capacityBits = total * 8
  bits.push(0, Math.min(4, capacityBits - bits.length))
  if (bits.length % 8 !== 0) bits.push(0, 8 - (bits.length % 8))
  const codewords = bits.toCodewords(total)
  // The standard's alternating pad bytes fill whatever is left.
  for (let i = bits.length / 8, pad = 0; i < total; i++, pad++) {
    codewords[i] = pad % 2 === 0 ? 0xec : 0x11
  }
  return codewords
}

/**
 * Split into blocks, add error correction, then interleave — a burst of damage
 * across the symbol has to land in several blocks rather than destroying one.
 */
const finalCodewords = (data: Uint8Array, version: number, level: QrLevel): Uint8Array => {
  const { ec, blocks: [group1, group2] } = EC[level][version]
  const count = group1 + group2
  // Group 2's blocks are exactly one codeword longer. Derived rather than
  // tabled, because a table that can be derived is a table that can be typed
  // in wrong — and v8-M (2x38 + 2x39) is the first version where getting it
  // wrong would not show up at any smaller version.
  const shortLength = Math.floor(data.length / count)
  const blocks: Uint8Array[] = []
  const ecBlocks: Uint8Array[] = []
  let offset = 0
  for (let i = 0; i < count; i++) {
    const length = i < group1 ? shortLength : shortLength + 1
    const block = data.slice(offset, offset + length)
    offset += length
    blocks.push(block)
    ecBlocks.push(reedSolomon(block, ec))
  }
  const out: number[] = []
  const longest = Math.max(...blocks.map((b) => b.length))
  for (let i = 0; i < longest; i++) {
    for (const block of blocks) if (i < block.length) out.push(block[i])
  }
  for (let i = 0; i < ec; i++) {
    for (const block of ecBlocks) out.push(block[i])
  }
  return Uint8Array.from(out)
}

// ---------------------------------------------------------------- matrix --

type Grid = { modules: boolean[][]; reserved: boolean[][] }

const blank = (n: number): Grid => ({
  modules: Array.from({ length: n }, () => new Array<boolean>(n).fill(false)),
  reserved: Array.from({ length: n }, () => new Array<boolean>(n).fill(false))
})

const setModule = (grid: Grid, row: number, col: number, dark: boolean): void => {
  grid.modules[row][col] = dark
  grid.reserved[row][col] = true
}

const finder = (grid: Grid, row: number, col: number): void => {
  for (let r = -1; r <= 7; r++) {
    for (let c = -1; c <= 7; c++) {
      const rr = row + r
      const cc = col + c
      if (rr < 0 || cc < 0 || rr >= grid.modules.length || cc >= grid.modules.length) continue
      const inner = r >= 0 && r <= 6 && c >= 0 && c <= 6
      const ring = r === 0 || r === 6 || c === 0 || c === 6
      const core = r >= 2 && r <= 4 && c >= 2 && c <= 4
      setModule(grid, rr, cc, inner && (ring || core))
    }
  }
}

const alignment = (grid: Grid, version: number): void => {
  const centres = ALIGNMENT[version]
  const last = size(version) - 1
  for (const row of centres) {
    for (const col of centres) {
      // The three finder corners already own their space.
      const atFinder =
        (row === 6 && col === 6) || (row === 6 && col === last - 6) || (row === last - 6 && col === 6)
      if (atFinder) continue
      for (let r = -2; r <= 2; r++) {
        for (let c = -2; c <= 2; c++) {
          setModule(grid, row + r, col + c, Math.max(Math.abs(r), Math.abs(c)) !== 1)
        }
      }
    }
  }
}

/** BCH(15,5) for the format string, and BCH(18,6) for the version string. */
const bch = (value: number, poly: number, bits: number, dataBits: number): number => {
  let rest = value << (bits - dataBits)
  for (let i = dataBits - 1; i >= 0; i--) {
    if (rest & (1 << (bits - dataBits + i))) rest ^= poly << i
  }
  return ((value << (bits - dataBits)) | rest) >>> 0
}

const formatBits = (level: QrLevel, mask: number): number =>
  (bch((LEVEL_BITS[level] << 3) | mask, 0x537, 15, 5) ^ 0x5412) >>> 0

const versionBits = (version: number): number => bch(version, 0x1f25, 18, 6)

/**
 * Where the 18 version-information bits sit, twice — once above the
 * bottom-left finder and once left of the top-right one. Version 6 and below
 * carry none, and the empty list is the whole of that fact.
 */
const versionInfoCells = (version: number): [number, number][] => {
  if (version < 7) return []
  const n = size(version)
  const cells: [number, number][] = []
  for (let i = 0; i < 18; i++) {
    cells.push([Math.floor(i / 3), n - 11 + (i % 3)])
    cells.push([n - 11 + (i % 3), Math.floor(i / 3)])
  }
  return cells
}

const drawFunctionPatterns = (grid: Grid, version: number): void => {
  const n = size(version)
  finder(grid, 0, 0)
  finder(grid, 0, n - 7)
  finder(grid, n - 7, 0)
  for (let i = 8; i < n - 8; i++) {
    setModule(grid, 6, i, i % 2 === 0)
    setModule(grid, i, 6, i % 2 === 0)
  }
  alignment(grid, version)
  // Always dark, always in the same place.
  setModule(grid, n - 8, 8, true)
  // Reserve the format areas; their contents depend on the mask.
  for (let i = 0; i < 9; i++) {
    if (!grid.reserved[8][i]) setModule(grid, 8, i, false)
    if (!grid.reserved[i][8]) setModule(grid, i, 8, false)
  }
  for (let i = 0; i < 8; i++) {
    if (!grid.reserved[8][n - 1 - i]) setModule(grid, 8, n - 1 - i, false)
    if (!grid.reserved[n - 1 - i][8]) setModule(grid, n - 1 - i, 8, false)
  }
  if (version >= 7) {
    const bits = versionBits(version)
    for (let i = 0; i < 18; i++) {
      const dark = ((bits >> i) & 1) === 1
      setModule(grid, Math.floor(i / 3), n - 11 + (i % 3), dark)
      setModule(grid, n - 11 + (i % 3), Math.floor(i / 3), dark)
    }
  }
}

const placeData = (grid: Grid, codewords: Uint8Array, version: number): void => {
  const n = size(version)
  let bit = 0
  let upward = true
  for (let right = n - 1; right >= 1; right -= 2) {
    // Column 6 is the vertical timing pattern; the zigzag steps over it.
    const pair = right === 6 ? 5 : right
    for (let step = 0; step < n; step++) {
      const row = upward ? n - 1 - step : step
      for (const col of [pair, pair - 1]) {
        if (grid.reserved[row][col]) continue
        const byte = codewords[bit >> 3]
        grid.modules[row][col] = byte !== undefined && ((byte >> (7 - (bit & 7))) & 1) === 1
        bit++
      }
    }
    upward = !upward
    if (right === 6) right -= 1
  }
}

const MASKS: ((row: number, col: number) => boolean)[] = [
  (r, c) => (r + c) % 2 === 0,
  (r) => r % 2 === 0,
  (_r, c) => c % 3 === 0,
  (r, c) => (r + c) % 3 === 0,
  (r, c) => (Math.floor(r / 2) + Math.floor(c / 3)) % 2 === 0,
  (r, c) => ((r * c) % 2) + ((r * c) % 3) === 0,
  (r, c) => (((r * c) % 2) + ((r * c) % 3)) % 2 === 0,
  (r, c) => (((r + c) % 2) + ((r * c) % 3)) % 2 === 0
]

const applyMask = (grid: Grid, mask: number): boolean[][] =>
  grid.modules.map((row, r) =>
    row.map((dark, c) => (grid.reserved[r][c] ? dark : dark !== MASKS[mask](r, c)))
  )

const writeFormat = (modules: boolean[][], level: QrLevel, mask: number): void => {
  const n = modules.length
  const bits = formatBits(level, mask)
  for (let i = 0; i < 15; i++) {
    const dark = ((bits >> i) & 1) === 1
    // The two copies, laid out the way the standard puts them.
    if (i < 6) modules[i][8] = dark
    else if (i === 6) modules[7][8] = dark
    else if (i === 7) modules[8][8] = dark
    else if (i === 8) modules[8][7] = dark
    else modules[8][14 - i] = dark

    if (i < 8) modules[8][n - 1 - i] = dark
    else modules[n - 15 + i][8] = dark
  }
  modules[n - 8][8] = true
}

/** The standard's four penalty rules — the mask with the lowest score wins. */
const penalty = (modules: boolean[][]): number => {
  const n = modules.length
  let score = 0

  const run = (get: (i: number, j: number) => boolean): void => {
    for (let i = 0; i < n; i++) {
      let length = 1
      for (let j = 1; j < n; j++) {
        if (get(i, j) === get(i, j - 1)) {
          length++
        } else {
          if (length >= 5) score += length - 2
          length = 1
        }
      }
      if (length >= 5) score += length - 2
    }
  }
  run((i, j) => modules[i][j])
  run((i, j) => modules[j][i])

  for (let r = 0; r < n - 1; r++) {
    for (let c = 0; c < n - 1; c++) {
      const first = modules[r][c]
      if (
        first === modules[r][c + 1] &&
        first === modules[r + 1][c] &&
        first === modules[r + 1][c + 1]
      ) {
        score += 3
      }
    }
  }

  const finderish = [true, false, true, true, true, false, true]
  const matches = (cells: boolean[], at: number): boolean =>
    finderish.every((want, i) => cells[at + i] === want)
  const clear = (cells: boolean[], from: number, to: number): boolean => {
    for (let i = from; i < to; i++) if (cells[i]) return false
    return true
  }
  const scanLine = (cells: boolean[]): void => {
    for (let i = 0; i + 7 <= n; i++) {
      if (!matches(cells, i)) continue
      if (i >= 4 && clear(cells, i - 4, i)) score += 40
      if (i + 11 <= n && clear(cells, i + 7, i + 11)) score += 40
    }
  }
  for (let i = 0; i < n; i++) {
    scanLine(modules[i])
    scanLine(modules.map((row) => row[i]))
  }

  const dark = modules.flat().filter(Boolean).length
  const percent = (dark * 100) / (n * n)
  score += Math.floor(Math.abs(percent - 50) / 5) * 10
  return score
}

/**
 * The QR for `text` as a square of booleans, dark = true, no quiet zone.
 * Returns null when the text is longer than a version-10 symbol can carry.
 *
 * NO QUIET ZONE IS RETURNED, and every caller owes the symbol four light
 * modules on all four sides. It is not decoration — a scanner finds the symbol
 * by that margin — and it is left to the caller because the caller is the one
 * that knows what colour its paper is.
 */
export const qrMatrix = (text: string, level: QrLevel = 'M'): boolean[][] | null => {
  const version = qrVersionFor(utf8(text).length, level)
  if (version === null) return null
  const grid = blank(size(version))
  drawFunctionPatterns(grid, version)
  placeData(grid, finalCodewords(dataCodewordsFor(text, version, level), version, level), version)

  /**
   * THE MASK IS SCORED WITH EVERY LATE-WRITTEN MODULE BLANK.
   *
   * The eight penalty rules are a legibility heuristic over the encoding
   * region. Three things are not part of that region and are written after
   * the mask has been chosen: the format strip, the always-dark module at
   * (n-8, 8), and — from version 7 up — the two version-information blocks.
   * The reference implementation these fixtures come from scores its
   * candidates with all three still blank.
   *
   * Every mask this picks is a legal, scannable one either way; a symbol
   * masked differently decodes identically, and the penalties the two
   * conventions produced were within a few per cent of each other in both
   * directions. So this is not a fix to the SYMBOL — it is a fix to the only
   * correctness check available, because a whole-matrix comparison cannot
   * tell a tie broken differently apart from a broken encoder.
   *
   * Missing the version blocks is what made versions 7 to 10 disagree with
   * the reference on roughly one payload in six while versions 1 to 6 — which
   * carry no version information at all — matched perfectly. The original
   * fixture sweep covered ten versions at one level and read that as noise.
   */
  const scored = (mask: number): number => {
    const candidate = applyMask(grid, mask)
    candidate[candidate.length - 8][8] = false
    for (const [row, col] of versionInfoCells(version)) candidate[row][col] = false
    return penalty(candidate)
  }

  let best = 0
  let bestScore = Infinity
  for (let mask = 0; mask < 8; mask++) {
    const score = scored(mask)
    if (score < bestScore) {
      bestScore = score
      best = mask
    }
  }
  const chosen = applyMask(grid, best)
  writeFormat(chosen, level, best)
  return chosen
}

/** An SVG path covering every dark module, for a one-element QR in the DOM. */
export const qrPath = (modules: boolean[][]): string =>
  modules
    .flatMap((row, r) =>
      row.map((dark, c) => (dark ? `M${c} ${r}h1v1h-1z` : '')).filter((d) => d.length > 0)
    )
    .join('')
