/**
 * A QR encoder, byte mode, error correction M, versions 1 to 10.
 *
 * WHY THIS IS HERE AND NOT A DEPENDENCY. The pairing popout has to draw a QR
 * in the renderer. The one QR library in the tree is `qrcode-terminal`, which
 * writes block characters to a TTY from the CLI — it is a printer, not an
 * encoder, and nothing in the browser bundle can use it. The alternative was a
 * new runtime dependency in the one window that shows a credential.
 *
 * Scope is deliberately narrow: one mode, one correction level, ten versions.
 * That covers every string this app puts on a screen — a 55-character pairing
 * payload, and a legacy tailnet URL with a token on it at about 80 — with room
 * left over, and it leaves out the numeric/alphanumeric/kanji modes, the ECI
 * header and structured append, which nothing here would ever emit.
 *
 * Correctness is not argued, it is checked: the tests compare whole matrices,
 * module for module, against fixtures generated by an independent reference
 * implementation. A QR that renders but does not scan is worse than no QR, and
 * a shape test would not catch one.
 */

/** Data codewords per version at correction level M. */
const TOTAL_CODEWORDS = [0, 26, 44, 70, 100, 134, 172, 196, 242, 292, 346]

/** [error-correction codewords per block, block count, ...] at level M. */
const EC_PER_BLOCK = [0, 10, 16, 26, 18, 24, 16, 18, 22, 22, 26]

/** Block counts per version at level M: [group1 blocks, group2 blocks]. */
const BLOCKS = [
  [0, 0], [1, 0], [1, 0], [1, 0], [2, 0], [2, 0],
  [4, 0], [4, 0], [2, 2], [3, 2], [4, 1]
]

/** Alignment-pattern centre coordinates per version. */
const ALIGNMENT = [
  [], [], [6, 18], [6, 22], [6, 26], [6, 30], [6, 34],
  [6, 22, 38], [6, 24, 42], [6, 26, 46], [6, 28, 50]
]

export const QR_MAX_VERSION = 10

const size = (version: number): number => version * 4 + 17

/** Byte-mode payload capacity, in bytes, at level M. */
export const qrCapacity = (version: number): number => {
  const dataCodewords = TOTAL_CODEWORDS[version] - ecCodewords(version)
  // 4 bits of mode + the character-count field, rounded down to whole bytes.
  const countBits = version < 10 ? 8 : 16
  return Math.floor((dataCodewords * 8 - 4 - countBits) / 8)
}

const ecCodewords = (version: number): number =>
  EC_PER_BLOCK[version] * (BLOCKS[version][0] + BLOCKS[version][1])

// ---------------------------------------------------------------- GF(256) --

const EXP = new Uint8Array(512)
const LOG = new Uint8Array(256)
{
  let x = 1
  for (let i = 0; i < 255; i++) {
    EXP[i] = x
    LOG[x] = i
    x <<= 1
    if (x & 0x100) x ^= 0x11d
  }
  for (let i = 255; i < 512; i++) EXP[i] = EXP[i - 255]
}

const gfMul = (a: number, b: number): number =>
  a === 0 || b === 0 ? 0 : EXP[LOG[a] + LOG[b]]

/** The generator polynomial for `degree` error-correction codewords. */
const generator = (degree: number): Uint8Array => {
  let poly = Uint8Array.from([1])
  for (let i = 0; i < degree; i++) {
    const next = new Uint8Array(poly.length + 1)
    for (let j = 0; j < poly.length; j++) {
      next[j] ^= poly[j]
      next[j + 1] ^= gfMul(poly[j], EXP[i])
    }
    poly = next
  }
  return poly
}

const reedSolomon = (data: Uint8Array, degree: number): Uint8Array => {
  const gen = generator(degree)
  const remainder = new Uint8Array(degree)
  for (const byte of data) {
    const factor = byte ^ remainder[0]
    remainder.copyWithin(0, 1)
    remainder[degree - 1] = 0
    for (let j = 0; j < degree; j++) remainder[j] ^= gfMul(gen[j + 1], factor)
  }
  return remainder
}

// ------------------------------------------------------------------ bits --

class Bits {
  private readonly bits: number[] = []

  push(value: number, length: number): void {
    for (let i = length - 1; i >= 0; i--) this.bits.push((value >> i) & 1)
  }

  get length(): number {
    return this.bits.length
  }

  toCodewords(count: number): Uint8Array {
    const out = new Uint8Array(count)
    for (let i = 0; i < this.bits.length; i++) {
      if (this.bits[i]) out[i >> 3] |= 0x80 >> (i & 7)
    }
    return out
  }
}

const utf8 = (text: string): Uint8Array => new TextEncoder().encode(text)

/** The smallest version at level M that holds `bytes`, or null if none does. */
export const qrVersionFor = (bytes: number): number | null => {
  for (let version = 1; version <= QR_MAX_VERSION; version++) {
    if (bytes <= qrCapacity(version)) return version
  }
  return null
}

const dataCodewordsFor = (text: string, version: number): Uint8Array => {
  const bytes = utf8(text)
  const total = TOTAL_CODEWORDS[version] - ecCodewords(version)
  const bits = new Bits()
  bits.push(0b0100, 4) // byte mode
  bits.push(bytes.length, version < 10 ? 8 : 16)
  for (const byte of bytes) bits.push(byte, 8)
  // Terminator, up to four zero bits, then pad to a whole byte.
  const capacityBits = total * 8
  bits.push(0, Math.min(4, capacityBits - bits.length))
  if (bits.length % 8 !== 0) bits.push(0, 8 - (bits.length % 8))
  const codewords = bits.toCodewords(total)
  // The standard's alternating pad bytes fill whatever is left.
  for (let i = bits.length / 8, pad = 0; i < total; i++, pad++) {
    codewords[i] = pad % 2 === 0 ? 0xec : 0x11
  }
  return codewords
}

/**
 * Split into blocks, add error correction, then interleave — a burst of damage
 * across the symbol has to land in several blocks rather than destroying one.
 */
const finalCodewords = (data: Uint8Array, version: number): Uint8Array => {
  const [group1, group2] = BLOCKS[version]
  const blockCount = group1 + group2
  const shortLength = Math.floor(data.length / blockCount)
  const blocks: Uint8Array[] = []
  const ecBlocks: Uint8Array[] = []
  let offset = 0
  for (let i = 0; i < blockCount; i++) {
    const length = i < group1 ? shortLength : shortLength + 1
    const block = data.slice(offset, offset + length)
    offset += length
    blocks.push(block)
    ecBlocks.push(reedSolomon(block, EC_PER_BLOCK[version]))
  }
  const out: number[] = []
  const longest = Math.max(...blocks.map((b) => b.length))
  for (let i = 0; i < longest; i++) {
    for (const block of blocks) if (i < block.length) out.push(block[i])
  }
  for (let i = 0; i < EC_PER_BLOCK[version]; i++) {
    for (const block of ecBlocks) out.push(block[i])
  }
  return Uint8Array.from(out)
}

// ---------------------------------------------------------------- matrix --

type Grid = { modules: boolean[][]; reserved: boolean[][] }

const blank = (n: number): Grid => ({
  modules: Array.from({ length: n }, () => new Array<boolean>(n).fill(false)),
  reserved: Array.from({ length: n }, () => new Array<boolean>(n).fill(false))
})

const setModule = (grid: Grid, row: number, col: number, dark: boolean): void => {
  grid.modules[row][col] = dark
  grid.reserved[row][col] = true
}

const finder = (grid: Grid, row: number, col: number): void => {
  for (let r = -1; r <= 7; r++) {
    for (let c = -1; c <= 7; c++) {
      const rr = row + r
      const cc = col + c
      if (rr < 0 || cc < 0 || rr >= grid.modules.length || cc >= grid.modules.length) continue
      const inner = r >= 0 && r <= 6 && c >= 0 && c <= 6
      const ring = r === 0 || r === 6 || c === 0 || c === 6
      const core = r >= 2 && r <= 4 && c >= 2 && c <= 4
      setModule(grid, rr, cc, inner && (ring || core))
    }
  }
}

const alignment = (grid: Grid, version: number): void => {
  const centres = ALIGNMENT[version]
  const last = size(version) - 1
  for (const row of centres) {
    for (const col of centres) {
      // The three finder corners already own their space.
      const atFinder =
        (row === 6 && col === 6) || (row === 6 && col === last - 6) || (row === last - 6 && col === 6)
      if (atFinder) continue
      for (let r = -2; r <= 2; r++) {
        for (let c = -2; c <= 2; c++) {
          setModule(grid, row + r, col + c, Math.max(Math.abs(r), Math.abs(c)) !== 1)
        }
      }
    }
  }
}

/** BCH(15,5) for the format string, and BCH(18,6) for the version string. */
const bch = (value: number, poly: number, bits: number, dataBits: number): number => {
  let rest = value << (bits - dataBits)
  for (let i = dataBits - 1; i >= 0; i--) {
    if (rest & (1 << (bits - dataBits + i))) rest ^= poly << i
  }
  return ((value << (bits - dataBits)) | rest) >>> 0
}

const formatBits = (mask: number): number =>
  // 0b00 is level M in the format field.
  (bch((0b00 << 3) | mask, 0x537, 15, 5) ^ 0x5412) >>> 0

const versionBits = (version: number): number => bch(version, 0x1f25, 18, 6)

const drawFunctionPatterns = (grid: Grid, version: number): void => {
  const n = size(version)
  finder(grid, 0, 0)
  finder(grid, 0, n - 7)
  finder(grid, n - 7, 0)
  for (let i = 8; i < n - 8; i++) {
    setModule(grid, 6, i, i % 2 === 0)
    setModule(grid, i, 6, i % 2 === 0)
  }
  alignment(grid, version)
  // Always dark, always in the same place.
  setModule(grid, n - 8, 8, true)
  // Reserve the format areas; their contents depend on the mask.
  for (let i = 0; i < 9; i++) {
    if (!grid.reserved[8][i]) setModule(grid, 8, i, false)
    if (!grid.reserved[i][8]) setModule(grid, i, 8, false)
  }
  for (let i = 0; i < 8; i++) {
    if (!grid.reserved[8][n - 1 - i]) setModule(grid, 8, n - 1 - i, false)
    if (!grid.reserved[n - 1 - i][8]) setModule(grid, n - 1 - i, 8, false)
  }
  if (version >= 7) {
    const bits = versionBits(version)
    for (let i = 0; i < 18; i++) {
      const dark = ((bits >> i) & 1) === 1
      setModule(grid, Math.floor(i / 3), n - 11 + (i % 3), dark)
      setModule(grid, n - 11 + (i % 3), Math.floor(i / 3), dark)
    }
  }
}

const placeData = (grid: Grid, codewords: Uint8Array, version: number): void => {
  const n = size(version)
  let bit = 0
  let upward = true
  for (let right = n - 1; right >= 1; right -= 2) {
    // Column 6 is the vertical timing pattern; the zigzag steps over it.
    const pair = right === 6 ? 5 : right
    for (let step = 0; step < n; step++) {
      const row = upward ? n - 1 - step : step
      for (const col of [pair, pair - 1]) {
        if (grid.reserved[row][col]) continue
        const byte = codewords[bit >> 3]
        grid.modules[row][col] = byte !== undefined && ((byte >> (7 - (bit & 7))) & 1) === 1
        bit++
      }
    }
    upward = !upward
    if (right === 6) right -= 1
  }
}

const MASKS: ((row: number, col: number) => boolean)[] = [
  (r, c) => (r + c) % 2 === 0,
  (r) => r % 2 === 0,
  (_r, c) => c % 3 === 0,
  (r, c) => (r + c) % 3 === 0,
  (r, c) => (Math.floor(r / 2) + Math.floor(c / 3)) % 2 === 0,
  (r, c) => ((r * c) % 2) + ((r * c) % 3) === 0,
  (r, c) => (((r * c) % 2) + ((r * c) % 3)) % 2 === 0,
  (r, c) => (((r + c) % 2) + ((r * c) % 3)) % 2 === 0
]

const applyMask = (grid: Grid, mask: number): boolean[][] =>
  grid.modules.map((row, r) =>
    row.map((dark, c) => (grid.reserved[r][c] ? dark : dark !== MASKS[mask](r, c)))
  )

const writeFormat = (modules: boolean[][], mask: number): void => {
  const n = modules.length
  const bits = formatBits(mask)
  for (let i = 0; i < 15; i++) {
    const dark = ((bits >> i) & 1) === 1
    // The two copies, laid out the way the standard puts them.
    if (i < 6) modules[i][8] = dark
    else if (i === 6) modules[7][8] = dark
    else if (i === 7) modules[8][8] = dark
    else if (i === 8) modules[8][7] = dark
    else modules[8][14 - i] = dark

    if (i < 8) modules[8][n - 1 - i] = dark
    else modules[n - 15 + i][8] = dark
  }
  modules[n - 8][8] = true
}

/** The standard's four penalty rules — the mask with the lowest score wins. */
const penalty = (modules: boolean[][]): number => {
  const n = modules.length
  let score = 0

  const run = (get: (i: number, j: number) => boolean): void => {
    for (let i = 0; i < n; i++) {
      let length = 1
      for (let j = 1; j < n; j++) {
        if (get(i, j) === get(i, j - 1)) {
          length++
        } else {
          if (length >= 5) score += length - 2
          length = 1
        }
      }
      if (length >= 5) score += length - 2
    }
  }
  run((i, j) => modules[i][j])
  run((i, j) => modules[j][i])

  for (let r = 0; r < n - 1; r++) {
    for (let c = 0; c < n - 1; c++) {
      const first = modules[r][c]
      if (
        first === modules[r][c + 1] &&
        first === modules[r + 1][c] &&
        first === modules[r + 1][c + 1]
      ) {
        score += 3
      }
    }
  }

  const finderish = [true, false, true, true, true, false, true]
  const matches = (cells: boolean[], at: number): boolean =>
    finderish.every((want, i) => cells[at + i] === want)
  const clear = (cells: boolean[], from: number, to: number): boolean => {
    for (let i = from; i < to; i++) if (cells[i]) return false
    return true
  }
  const scanLine = (cells: boolean[]): void => {
    for (let i = 0; i + 7 <= n; i++) {
      if (!matches(cells, i)) continue
      if (i >= 4 && clear(cells, i - 4, i)) score += 40
      if (i + 11 <= n && clear(cells, i + 7, i + 11)) score += 40
    }
  }
  for (let i = 0; i < n; i++) {
    scanLine(modules[i])
    scanLine(modules.map((row) => row[i]))
  }

  const dark = modules.flat().filter(Boolean).length
  const percent = (dark * 100) / (n * n)
  score += Math.floor(Math.abs(percent - 50) / 5) * 10
  return score
}

/**
 * The QR for `text` as a square of booleans, dark = true, no quiet zone.
 * Returns null when the text is longer than a version-10 symbol can carry.
 */
export const qrMatrix = (text: string): boolean[][] | null => {
  const version = qrVersionFor(utf8(text).length)
  if (version === null) return null
  const grid = blank(size(version))
  drawFunctionPatterns(grid, version)
  placeData(grid, finalCodewords(dataCodewordsFor(text, version), version), version)

  // THE MASK IS SCORED BEFORE THE FORMAT BITS GO ON.
  //
  // The eight penalty rules are a legibility heuristic over the encoding
  // region, and the format strip is not part of it — so the strip stays light
  // while the masks are compared, exactly as the reference implementation the
  // fixtures come from does it. It matters only when two masks tie, which is
  // often for small symbols: 'A' scores 355 under both mask 3 and mask 4, and
  // whichever convention is used has to be used consistently or the whole
  // matrix drifts from the reference by half its modules. Both symbols scan;
  // only one can be compared.
  let best = 0
  let bestScore = Infinity
  for (let mask = 0; mask < 8; mask++) {
    const score = penalty(applyMask(grid, mask))
    if (score < bestScore) {
      bestScore = score
      best = mask
    }
  }
  const chosen = applyMask(grid, best)
  writeFormat(chosen, best)
  return chosen
}

/** An SVG path covering every dark module, for a one-element QR in the DOM. */
export const qrPath = (modules: boolean[][]): string =>
  modules
    .flatMap((row, r) =>
      row.map((dark, c) => (dark ? `M${c} ${r}h1v1h-1z` : '')).filter((d) => d.length > 0)
    )
    .join('')
