// Pure pieces of the CLI installer, split from install-cli.mjs so tests can
// import them. The split is not cosmetic: the executable script carries a
// shebang, and vite-node on WINDOWS inlines (rather than externalizes) a
// project .mjs import — the unstripped `#!` then reaches the module runner as
// invalid JS and the whole suite dies with "Invalid or unexpected token".
// On macOS/Linux the same import externalizes to a native node import, which
// strips shebangs, which is why the failure was windows-only.

/**
 * Where to install.
 *
 * Preference order is about NOT needing sudo: a user-owned dir already on PATH
 * beats a system one that would need elevation. /usr/local/bin is last and only
 * if it is genuinely writable.
 */
export function pickBinDir(candidates, isWritable) {
  return candidates.find((dir) => isWritable(dir)) ?? null
}

/**
 * The launcher. POSIX sh so it does not depend on the user's shell.
 *
 * The node interpreter is BAKED IN as an absolute path, not left as `node`.
 * A bare `node` resolves against the caller's PATH, and the shells most likely
 * to reach for this CLI are the ones least likely to have it: a GUI-launched
 * terminal, a cron entry, a stripped `env -i` shell. Measured — `exec: node:
 * not found` on a minimal PATH. The PATH lookup stays as a fallback for the
 * case where the baked interpreter is later removed (a node upgrade).
 */
export function launcherScript(runtimeCli, repoCli, nodeBin) {
  return [
    '#!/bin/sh',
    '# Generated by cookrew (scripts/install-cli.mjs). Resolves the CLI at run',
    '# time: the app runtime copy first, this checkout as the fallback.',
    `RUNTIME="${runtimeCli}"`,
    `REPO="${repoCli}"`,
    `NODE="${nodeBin}"`,
    '[ -x "$NODE" ] || NODE="$(command -v node 2>/dev/null)"',
    'if [ -z "$NODE" ]; then',
    '  echo "cookrew: node not found. Reinstall with: npm run install-cli" >&2',
    '  exit 1',
    'fi',
    // REPO first: it only exists in a dev checkout, and there it is the
    // source of truth. The app rewrites the runtime copy from it at launch,
    // so preferring runtime meant edits did not take effect until a restart
    // (measured: a stale runtime copy answered with the pre-edit behaviour).
    // A packaged install has no repo path, so runtime wins there.
    'if [ -f "$REPO" ]; then exec "$NODE" "$REPO" "$@"; fi',
    'if [ -f "$RUNTIME" ]; then exec "$NODE" "$RUNTIME" "$@"; fi',
    'echo "cookrew: CLI not found. Launch the Cookrew app once, or reinstall with:" >&2',
    'echo "  npm run install-cli" >&2',
    'exit 1',
    ''
  ].join('\n')
}
