// Generates registry/src/assets-bundle.ts from registry/assets/{vendor,*.js,*.css}.
//
// The registry ships as ONE esbuild bundle (a ConfigMap on the cluster, a
// single file under systemd), so anything it serves as a static asset has to
// travel inside that bundle. This turns the vendored xterm.js, the site's own
// scripts and their stylesheets into string constants; the bundle build runs
// it first (`npm run registry:build`), and the generated file is committed so
// tests and type-checks see the same bytes production serves.
import { readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const assets = path.join(root, 'registry', 'assets')

/** name on the wire → source file, content type. */
const FILES = [
  ['xterm.js', 'vendor/xterm.js.txt', 'text/javascript; charset=utf-8'],
  ['xterm.css', 'vendor/xterm.css.txt', 'text/css; charset=utf-8'],
  ['addon-fit.js', 'vendor/addon-fit.js.txt', 'text/javascript; charset=utf-8'],
  ['site.js', 'site.js', 'text/javascript; charset=utf-8'],
  ['line.js', 'line.js', 'text/javascript; charset=utf-8']
]

const entries = FILES.map(([name, file, type]) => {
  const body = readFileSync(path.join(assets, file), 'utf8')
  return `  ${JSON.stringify(name)}: { type: ${JSON.stringify(type)}, body: ${JSON.stringify(body)} }`
})

const out = `// GENERATED by scripts/registry-assets.mjs — do not edit. Sources: registry/assets/.
export interface BundledAsset {
  type: string
  body: string
}

export const ASSETS: Readonly<Record<string, BundledAsset>> = {
${entries.join(',\n')}
}
`
writeFileSync(path.join(root, 'registry', 'src', 'assets-bundle.ts'), out)
console.log(`assets-bundle.ts: ${FILES.length} files, ${(out.length / 1024).toFixed(0)} KB`)
