// Generates registry/src/assets-bundle.ts from registry/assets/{vendor,*.js,*.css}.
//
// The registry ships as ONE esbuild bundle (a ConfigMap on the cluster, a
// single file under systemd), so anything it serves as a static asset has to
// travel inside that bundle. This turns the vendored xterm.js, the site's own
// scripts and their stylesheets into string constants; the bundle build runs
// it first (`npm run registry:build`), and the generated file is committed so
// tests and type-checks see the same bytes production serves.
import { readFileSync, writeFileSync } from 'node:fs'
import { createHash } from 'node:crypto'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const assets = path.join(root, 'registry', 'assets')

/** name on the wire → source file, content type. */
const FILES = [
  ['xterm.js', 'vendor/xterm.js.txt', 'text/javascript; charset=utf-8'],
  ['xterm.css', 'vendor/xterm.css.txt', 'text/css; charset=utf-8'],
  ['addon-fit.js', 'vendor/addon-fit.js.txt', 'text/javascript; charset=utf-8'],
  ['site.js', 'site.js', 'text/javascript; charset=utf-8'],
  ['seal.js', 'seal.js', 'text/javascript; charset=utf-8'],
  ['line.js', 'line.js', 'text/javascript; charset=utf-8'],
  ['inter.woff2', 'fonts/inter.woff2', 'font/woff2', 'base64'],
  ['jetbrains-mono.woff2', 'fonts/jetbrains-mono.woff2', 'font/woff2', 'base64'],
  ['silkscreen-400.woff2', 'fonts/silkscreen-400.woff2', 'font/woff2', 'base64'],
  ['silkscreen-700.woff2', 'fonts/silkscreen-700.woff2', 'font/woff2', 'base64'],
  ['vt323-400.woff2', 'fonts/vt323-400.woff2', 'font/woff2', 'base64']
]

const entries = FILES.map(([name, file, type, encoding]) => {
  const body = encoding === 'base64' ? readFileSync(path.join(assets, file)).toString('base64') : readFileSync(path.join(assets, file), 'utf8')
  return `  ${JSON.stringify(name)}: { type: ${JSON.stringify(type)}, body: ${JSON.stringify(body)}${encoding === 'base64' ? ", encoding: 'base64'" : ''} }`
})

const version = createHash('sha256').update(entries.join('\n')).digest('hex').slice(0, 12)
const out = `// GENERATED by scripts/registry-assets.mjs — do not edit. Sources: registry/assets/.
/** A content hash of every asset: pages link /assets/x?v=… so a new bundle is never a stale script. */
export const ASSET_VERSION = ${JSON.stringify(version)}

export interface BundledAsset {
  type: string
  body: string
  /** Binary assets travel as base64; text ones as they are. */
  encoding?: 'base64'
}

export const ASSETS: Readonly<Record<string, BundledAsset>> = {
${entries.join(',\n')}
}
`
writeFileSync(path.join(root, 'registry', 'src', 'assets-bundle.ts'), out)
console.log(`assets-bundle.ts: ${FILES.length} files, ${(out.length / 1024).toFixed(0)} KB`)
